add Vietnamese
mydoge-com/wallet-translations pull request #1
Opened 2024-07-09 23:49 UTC by hieujson

2024-07-12 08:23 UTC, kinaskitaro commented
add vietnamese plz

2024-07-12 08:33 UTC, phamducvu commented
add Vietnamese, thank you!

2024-07-16 19:29 UTC, alexanvl requested changes
Please fix the language settings translations and I will approve and merge this for release. Thank you!

2024-07-16 19:29 UTC, alexanvl commented on en.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on es.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on fr.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on ja.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on ko.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on pt.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on zh.js
> +    vn: 'Vietnamese',
Language setting should be translated

2024-07-16 19:29 UTC, alexanvl commented on vn.js
> +        en: 'Tiếng Anh',
Individual language settings should be translated to the local language

2024-07-17 17:13 UTC, alexanvl approved these changes

2024-07-17 17:15 UTC, merged